# Common fields for all devices

properties:
    status:
        type: string
        category: optional
        description: indicates the operational status of a device
        enum:
           - "okay"
           - "disabled"
           - "reserved"
           - "fail"
           - "fail-sss"

    compatible:
        type: string-array
        category: required
        description: compatible strings

    reg:
        type: array
        description: register space
        category: optional

    reg-names:
        type: string-array
        description: name of each register space
        category: optional

    interrupts:
        type: array
        category: optional
        description: interrupts for device

    interrupts-extended:
        type: phandle-array
        category: optional
        description: extended interrupt specifier for device

    interrupt-names:
        type: string-array
        category: optional
        description: name of each interrupt

    interrupt-parent:
        type: phandle
        category: optional
        description: phandle to interrupt controller node

    label:
        type: string
        category: optional
        description: Human readable string describing the device (used by Zephyr for API name)

    clocks:
        type: phandle-array
        category: optional
        description: Clock gate information

    "#address-cells":
        type: int
        category: optional
        description: number of address cells in reg property

    "#size-cells":
        type: int
        category: optional
        description: number of size cells in reg property
