# Copyright (c) 2020 Linaro Limited.
# SPDX-License-Identifier: Apache-2.0

name: Documentation GitHub Workflow

on:
  pull_request:
    paths:
    - 'doc/**'
    - '**.rst'
    - 'include/**'
    - 'kernel/include/kernel_arch_interface.h'
    - 'lib/libc/**'
    - 'subsys/testsuite/ztest/include/**'
    - 'tests/**'
    - '**/Kconfig*'
    - 'west.yml'
    - '.github/workflows/doc-build.yml'
    - 'scripts/dts/**'
    - 'scripts/requirements-doc.txt'

jobs:
  doc-build-html:
    name: "Documentation Build (HTML)"
    runs-on: ubuntu-latest

    steps:
    - name: Update PATH for west
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: checkout
      uses: actions/checkout@v2

    - name: install-pkgs
      run: |
        sudo apt-get install -y ninja-build doxygen graphviz

    - name: cache-pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: pip-${{ hashFiles('scripts/requirements-doc.txt') }}

    - name: install-pip
      run: |
        sudo pip3 install -U setuptools wheel pip
        pip3 install -r scripts/requirements-doc.txt
        pip3 install west==0.11.0

    - name: west setup
      run: |
        west init -l .

    - name: build-docs
      run: |
        SPHINXOPTS="-q -W -j auto" make -C doc html

    - name: compress-docs
      run: |
        tar cfJ html-output.tar.xz --directory=doc/_build html

    - name: upload-build
      uses: actions/upload-artifact@master
      continue-on-error: True
      with:
        name: html-output
        path: html-output.tar.xz

  doc-build-pdf:
    name: "Documentation Build (PDF)"
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install-pkgs
      run: |
        apt-get update
        apt-get install -y python3-pip cmake ninja-build doxygen graphviz librsvg2-bin

    - name: cache-pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: pip-${{ hashFiles('scripts/requirements-doc.txt') }}

    - name: install-pip
      run: |
        pip3 install -U setuptools wheel pip
        pip3 install -r scripts/requirements-doc.txt
        pip3 install west==0.11.0

    - name: west setup
      run: |
        west init -l .

    - name: build-docs
      run: |
        SPHINXOPTS="-q -j auto" LATEXMKOPTS="-quiet -halt-on-error" make -C doc pdf

    - name: upload-build
      uses: actions/upload-artifact@master
      with:
        name: pdf-output
        path: doc/_build/latex/zephyr.pdf
